# Generated by Django 4.2.4 on 2023-11-01 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoAlgoritmo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtdTeste", models.FloatField()),
                ("qtdVizinhos", models.IntegerField()),
                ("algoritmo", models.CharField(max_length=15)),
                ("pesos", models.CharField(max_length=15)),
                ("acuracia", models.FloatField()),
                ("data_analise", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Analise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("N", models.IntegerField()),
                ("P", models.IntegerField()),
                ("K", models.IntegerField()),
                ("Temperatura", models.FloatField()),
                ("Umidade", models.FloatField()),
                ("pH", models.FloatField()),
                ("Chuva", models.FloatField()),
                ("Colheita", models.CharField(max_length=50)),
                ("data_analise", models.DateTimeField(auto_now_add=True)),
                (
                    "configuracao_algoritmo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analise.configuracaoalgoritmo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
