# Generated by Django 4.2.4 on 2023-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analise",
            name="Colheita",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
