# Generated by Django 4.2.4 on 2023-09-29 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analise", "0002_analise_colheita"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnaliseSolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_analise", models.DateField()),
                (
                    "analise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analise.analise",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
