# Generated by Django 4.2.4 on 2023-09-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("colheitas", "0001_initial"),
        ("analise", "0003_analisesolo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analise",
            name="Colheita",
        ),
        migrations.AddField(
            model_name="analise",
            name="colheita",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="colheitas.colheita",
            ),
            preserve_default=False,
        ),
    ]
