# Generated by Django 4.2.4 on 2023-09-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analise", "0004_remove_analise_colheita_analise_colheita"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analise",
            name="colheita",
        ),
        migrations.AddField(
            model_name="analise",
            name="Colheita",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
